### ISSUE TITLE
Error when parsing unicode symbols escaped on JSON side

### ISSUE THREAD

**Issue by alexander-yakushev** [gerritjvv/pjson#22]
Example:

```clojure
(pjson/read-str "[\"opportunity\\u0027s\",\"opportunities\"]")
=> ["opportunity\\0027s" "," true true "]"]
```

As you can see, the parser goes mad when it sees the part `\u0027`. Please notice the double-slash there to ensure that the string is a valid JSON escaping sequence, not a Unicode symbol to be parsed on Java side.

Now, I would mark it as the library tradeoff unless the documentation said:

> As for version 0.3.6 escaped characters are supported and correctly read, if a String with an escape character is detected the parser will drop into a slower parsing implementation that will read all escapes correctly.

What should I make of it? Is this a bug, or does that paragraph refer only to strings with Unicode characters already parsed by Java?

**Comment by gerritjvv** [comment]
this is a bug, thanks for reporting. I'm going to setup a test and fix it

**Comment by alexander-yakushev** [comment]
Thank you!

**Comment by gerritjvv** [comment]
@alexander-yakushev please try the latest snapshot 0.3.7-SNAPSHOT, 
Java syndrome makes you think escapes are single char \u[unicode].

I've also added a test that goes through all charsets as per http://www.w3schools.com/charsets/

**Comment by alexander-yakushev** [comment]
It works now! Thank you very much for the prompt response and fix.

**Comment by gerritjvv** [comment]
noprobs.
 :)
