### ISSUE TITLE
parser not reading -4.626E-4 correctly

### ISSUE THREAD

**Issue by gerritjvv** [gerritjvv/pjson#25]
```
(pjson/read-str "[-4.626E-4]")
[-4.626 -4]
```

is wrong

**Comment by darkleaf** [comment]
```clojure
(pjson/read-str "[1e+06]");; => [63 6]
```

```
pjson/pjson                {:mvn/version "0.5.2"}
```

**Comment by darkleaf** [comment]
```clojure
(pjson/read-str "[1.96264948324e+11]")
```
 ```
#error {
 :cause nil
 :via
 [{:type java.lang.NumberFormatException
   :message nil
   :at [java.math.BigDecimal <init> "BigDecimal.java" 688]}
  {:type java.lang.ArrayIndexOutOfBoundsException
   :message nil}]
 :trace
 []}
```

**Comment by gerritjvv** [comment]
Hi, @darkleaf thanks for reporting this. I'll investigate a bit during the week after work and see what's up.

**Comment by gerritjvv** [comment]
try  version `1.0.0-SNAPSHOT` I still want to run some tests and benchmarks. If you have any good test data (i.e numbers with scientific notation etc)  i can use plz attach to this issue.

**Comment by darkleaf** [comment]
Thank you for quick answer!

I don't need convenient api for my tasks so I've switched to [LazyJson](https://github.com/doubledutch/LazyJSON).
You library is awesome and it is known in Russian community 👍 

> plz attach to this issue.
Unfortunately I can't.

* "[1e+06]"
* "[1.96264948324e+11]"

**Comment by gerritjvv** [comment]
LazyJson seems like a cool project with very similar ideas. 
I didn't know my library was popular/known, so great to know.

Thanks again for reporting the issue,  I'll generate some more test cases and then make a release.

**Comment by gerritjvv** [comment]
this is included now in the latest version.
