### ISSUE TITLE
Incorrect parsing examples in README

### ISSUE THREAD

**Issue by jeroenvandijk** [gerritjvv/pjson#28]
Hi Gerrit,

Thank you for this library. 

During some testing I've found that there are some problems with the examples under "Validation" in the README:

## Example 1
This example under is actually giving a repl error and not an error from your library
```
(pjson/read-str "{\"abc\": bla, "\edf\":122}")
```
What you meant might have been:
```
 (pjson/read-str "{\"abc\": bla, \"edf\":122}")
```
This gives `{"abc" "edf"}`, but no error.

## Example 2
`(pjson/read-str "{\"abc\": bla}")` doesn't give a parser exception, but gives an empty map `{}`

**Comment by gerritjvv** [comment]
thanks, I'll update the examples in the readme

**Comment by gerritjvv** [comment]
https://github.com/gerritjvv/pjson/pull/29

updated and merged :)

**Comment by gerritjvv** [comment]
please feel free to reopen if you find any other such issues :)
